project:
  type: book
  output-dir: docs

book:
  title: "MA4J1 Continuum Mechanics Notes"
  author: "Thomas Hudson"
  date: "January 2025"
  chapters:
    - index.qmd
    - tensoralgebra.qmd
    - tensorcalculus.qmd
    - massandforces.qmd
    - kinematics.qmd
    - balancelaws.qmd
  downloads: pdf

format:
  html:
    toc: true
    html-math-method: katex
    css: styles.css
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrbook
    papersize: a4
    toc: true
    toc-depth: 2
    pdf-engine: pdflatex
    fontfamily: "domitian"
    mainfont: "Palatino"
    sansfont: "Palatino"
    mathfont: "Computer Modern Roman"