{{< include macros.qmd >}}

# Solid Mechanics {#sec-solids}

In this final chapter, we will apply the theory we have developed to the modelling of solid materials.

## Elasticity Theory
A body is an elastic solid if the following two conditions hold:

::: {.callout-important icon="false"}
## Elastic solid
1. The Cauchy stress can be expressed in terms of the deformation gradient via a
*response function* $\widehat{\bfS}:\calV^2\times B\to\calV^2$, i.e.
$$
\bfS_m(\bfx,t) = \widehat{\bfS}\big(\bfF(\bfx,t),\bfx\big)
$$
2. The response function $\widehat{\bfS}$ is symmetric, i.e.
$$
\widehat{\bfS}(\bfF,\bfx) = \widehat{\bfS}^T(\bfF,\bfx)
$$
for any $\bfx\in B$ and $\bfF\in\calV^2$ with $\det\bfF>0$.
:::

The first of these conditions says that the Cauchy stress is a function of strain only
(rather than strain rate). This is commonly observed for a wide range of solids. The
latter requirement ensures that angular momentum balance will always be satisfied, so we
do not have to solve these equations separately.

In general, we typically use the Lagrangian formalism to express the equations governing
solids. However, since we have assumed that the Cauchy stress is a prescribed function
$\widehat{\bfS}$, we have that the Piola-Kirchhoff stress takes the form
$$
\bfP = \widehat{\bfP}(\bfF,\bfx) = \det\bfF\,\widehat{\bfS}(\bfF,\bfx)\bfF^{-T}.
$$

### Examples of stress response functions
Some examples of functional forms used for $\widehat{\bfS}$ include:

1. The **Neo-Hookean** response function:
$$
\widehat{\bfS}(\bfF) = \frac{A(\bfF\bfF^T-\bfI)}{\det\bfF}+B(\det\bfF-1)\bfI,
$$
where $A$ and $B$ are material constants.
1. The **St Venant--Kirchhoff** response function:
$$
\widehat{\bfS}(\bfF) = \lambda\,\tr(\tfrac12(\bfF^T\bfF-\bfI))\bfF\bfF^T+\mu (\bfF\bfF^T\bfF\bfF^T-\bfF\bfF^T),
$$
where $\lambda$ and $\mu$ are material constants.

### Elastodynamics

### Frame indifference

## Linear Elasticity Theory
